import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <string> file_path: "No file selected";
    callback request_file();
    title: "Image Splitter";
    min-height: 150px;
    min-width: 600px;

    VerticalLayout {
        spacing: 10px;
        padding: 50px;
        Button {
            text: "Open file";
            clicked => {
                root.request_file();
            }
        }

        Text {
            text: root.file_path;
            horizontal-alignment: center;
        }
    }
}
